### ISSUE TITLE
Do we need some licensing statement

### ISSUE THREAD

**Issue by alessiogambi** [JUnitContest/junitcontest#13]
In some files there was/is a licensing statement. What should we do about it? Do we need to update and uniform all the files to have one?

**Comment by xdevroey** [comment]
That is what I tried to do in #11. If you have one general license statement at the root level, it is fine, right? 

We might need to add something about the licenses of the projects and tools that are in the repo?

**Comment by alessiogambi** [comment]
> That is what I tried to do in #11. If you have one general license statement at the root level, it is fine, right?

Maybe, I am not an expert. In some projects, every file has a license header, in others none

> We might need to add something about the licenses of the projects and tools that are in the repo?

If you mean the benchmarked classes, probably, it is enough to "ensure" that our licensing is not looser than theirs? As I said, I am not an expert in this matter :(

**Comment by spanichella** [comment]
Added the license here with commit 8a67b65
